# cookies_from_curl.py
#
# Converts a curl file from an exported request as CURL from Chrome to a
# Netscape HTTP Cookie file formatted output

import argparse
import re
import sys

def parse_curl_cookie_line(line):
  """
  Parse a line from Chrome's "copy as cURL" (containing -H 'cookie: ...')
  and return a list of (name, value) tuples.
  """
  # Regex to capture the content inside 'cookie: ...'
  pattern = r"-H\s'cookie:\s([^']*)'"
  match = re.search(pattern, line)
  if not match:
    return []

  cookie_string = match.group(1)

  # Split by semicolon to get individual cookies
  raw_cookies = cookie_string.split(';')

  cookies = []
  for raw_cookie in raw_cookies:
    raw_cookie = raw_cookie.strip()
    if '=' not in raw_cookie:
      continue
    name, value = raw_cookie.split('=', 1)
    cookies.append((name.strip(), value.strip()))
  return cookies

def print_netscape_cookies(cookies, domain="example.com"):
  """
  Print cookies in Netscape HTTP Cookie File format.
  """
  # Netscape Cookie File header
  print("# Netscape HTTP Cookie File")
  print("# This file was generated by a Python script.")
  print("# Format: <domain> <flag> <path> <secure> <expiration> <name> <value>")
  print()

  # For each cookie, print in the standard 7-column Netscape format:
  # domain, include_subdomains_flag, path, secure_flag, expiration, name, value
  # Adjust as needed (e.g. domain, secure flag, expiration).
  for name, value in cookies:
    # Example usage:
    domain_field = domain
    include_subdomains = "FALSE"     # or TRUE if you want to match subdomains
    path = "/"                       # path for which this cookie is valid
    secure = "FALSE"                 # or TRUE if cookie requires HTTPS
    expiration = "0"                 # 0 means session cookie; or specify a Unix timestamp
    print(f"{domain_field}\t{include_subdomains}\t{path}\t{secure}\t{expiration}\t{name}\t{value}")

def main():
  parser = argparse.ArgumentParser('cookies from curl file', description='Expects '
    'a curl file from exporting a request as CURL from chrome. Theyre fuggly.'
  )
  parser.add_argument('curl_file')
  args = parser.parse_args()
  with open(args.curl_file) as f:
    for line in f.read().split('\n'):
      if 'cookie' not in line:
        continue
      cookies = parse_curl_cookie_line(line)
      if not cookies:
        print("No cookies found in the provided line.")
        sys.exit(1)
      print_netscape_cookies(cookies)

if __name__ == '__main__':
  main()
